from typing import List

from sqlalchemy.orm import Session

from app.models.conversation import ConversationHistory
from app.repositories.conversation_repository import (
    ConversationRepository,
)



class ConversationService:
    """
    Service layer for managing user/AI conversations.

    Responsibilities:
    - Save user messages
    - Save assistant responses
    - Load recent conversation history
    """

    def __init__(self, db: Session):
        self.db = db

        self.conversation_repository = ConversationRepository(
            db
        )

    # ---------------------------------------------------------
    # Save User Message
    # ---------------------------------------------------------

    def save_user_message(
        self,
        user_id: int,
        message: str,
    ) -> ConversationHistory:
        """
        Save a message sent by the user.
        """

        return self.conversation_repository.save_message(
            user_id=user_id,
            role="user",
            message=message,
        )

    # ---------------------------------------------------------
    # Save Assistant Response
    # ---------------------------------------------------------

    def save_assistant_response(
        self,
        user_id: int,
        message: str,
    ) -> ConversationHistory:
        """
        Save the response generated by the AI assistant.
        """

        return self.conversation_repository.save_message(
            user_id=user_id,
            role="assistant",
            message=message,
        )

    # ---------------------------------------------------------
    # Get Recent Conversation
    # ---------------------------------------------------------

    def get_recent_messages(
        self,
        user_id: int,
        limit: int = 10,
    ) -> List[ConversationHistory]:
        """
        Load the last N messages for a user.

        Messages are returned in chronological order.
        """

        return self.conversation_repository.get_recent_messages(
            user_id=user_id,
            limit=limit,
        )

    # ---------------------------------------------------------
    # Save Complete Exchange
    # ---------------------------------------------------------

    def save_exchange(
        self,
        user_id: int,
        user_message: str,
        assistant_response: str,
    ) -> tuple[
        ConversationHistory,
        ConversationHistory,
    ]:
        """
        Save one complete user -> assistant exchange.

        Both messages are committed as one transaction.
        """

        try:

            user_message_record = (
                self.conversation_repository.save_message(
                    user_id=user_id,
                    role="user",
                    message=user_message,
                )
            )

            assistant_message_record = (
                self.conversation_repository.save_message(
                    user_id=user_id,
                    role="assistant",
                    message=assistant_response,
                )
            )

            self.db.commit()

            return (
                user_message_record,
                assistant_message_record,
            )

        except Exception:
            self.db.rollback()
            raise

    # ---------------------------------------------------------
    # Delete Old Conversation
    # ---------------------------------------------------------

    def delete_old_messages(
        self,
        user_id: int,
        days: int = 30,
    ) -> int:
        """
        Delete conversation messages older than the
        specified number of days.
        """

        try:

            deleted_count = (
                self.conversation_repository.delete_old_messages(
                    user_id=user_id,
                    days=days,
                )
            )

            self.db.commit()

            return deleted_count

        except Exception:
            self.db.rollback()
            raise
