"""create onboarding models

Revision ID: 78d97d3bcc0b
Revises: aba3a8cf91ce
Create Date: 2026-08-07 15:45:05.829912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78d97d3bcc0b'
down_revision: Union[str, Sequence[str], None] = 'aba3a8cf91ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('users', 'onboarding_completed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_constraint(op.f('users_telegram_id_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.drop_column('users', 'companies')
    op.drop_column('users', 'preferences')
    op.drop_column('users', 'role')
    op.drop_column('users', 'briefing_time')
    op.drop_column('users', 'market')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('market', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('briefing_time', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('preferences', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('companies', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_unique_constraint(op.f('users_telegram_id_key'), 'users', ['telegram_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'onboarding_completed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
