"""update user table

Revision ID: aba3a8cf91ce
Revises: 
Create Date: 2026-08-07 12:58:56.710333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aba3a8cf91ce'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telegram_id', sa.BigInteger(), nullable=False))
    op.add_column('users', sa.Column('full_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('companies', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('market', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('preferences', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('briefing_time', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('onboarding_completed', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['telegram_id'])
    op.drop_column('users', 'name')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'onboarding_completed')
    op.drop_column('users', 'briefing_time')
    op.drop_column('users', 'preferences')
    op.drop_column('users', 'market')
    op.drop_column('users', 'companies')
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'telegram_id')
    # ### end Alembic commands ###
